import kevin from '../../images/kevin-mueller-aeNg4YA41P8-unsplash.jpg'
import phillips from '../../images/philipp-pilz-iQRKBNKyRpo-unsplash.jpg'

export const blogCardData = [
    {
        id: '1',
        image: kevin,
        title: '6 Days trip to Africa',
        date: '12 - Feb',
        author: 'Admin',
        topP: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nisi cumque iure placeat repellendus saepe, iusto libero odio pariatur culpa vel magnam..",
        mainP: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, optio natus explicabo, sit praesentium accusamus, libero ullam impedit dolore quidem rem quasi nulla nostrum magni eligendi tempora quis dolorem. Aut.",
        guide: "Sam Alabama",
        p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, optio natus explicabo, sit praesentium accusamus, libero ullam impedit dolore quidem rem quasi nulla nostrum magni eligendi tempora quis dolorem. Aut.",
        p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, optio natus explicabo, sit praesentium accusamus, libero ullam impedit dolore quidem rem quasi nulla nostrum magni eligendi tempora quis dolorem. Aut. amet consectetur adipisicing elit. Nobis, optio natus explicabo, sit praesentium accusamus, libero ullam impedit dolore quidem rem quasi nulla nostrum magni eligendi tempora quis dolorem. Aut.",
        p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, optio natus explicabo, sit praesentium accusamus, libero ullam impedit dolore quidem rem quasi nulla nostrum magni eligendi tempora quis dolorem. Aut.",
        p4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, optio natus explicabo, sit praesentium accusamus, libero ullam impedit dolore quidem rem quasi nulla nostrum magni eligendi tempora quis dolorem. Aut. amet consectetur adipisicing elit. Nobis, optio natus explicabo, sit praesentium accusamus, libero ullam impedit dolore quidem rem quasi nulla nostrum magni eligendi tempora quis dolorem. Aut.",
    },
    {
        id: '2',
        image: phillips,
        title: 'A week in Paris',
        date: '2022-01-01',
        author: 'John Doe',
        topP: 'Paris, the city of love and romance, is a dream destination for many travelers around the world. I recently had the opportunity to spend a week in this beautiful city, and it was an experience of a lifetime.',
        mainP: 'During my stay in Paris, I visited many of its iconic landmarks, such as the Eiffel Tower, the Louvre Museum, and Notre-Dame Cathedral. I also explored the charming streets of Montmartre and tasted some delicious French cuisine in local restaurants.',
        guide: 'Sophie Martin',
        p1: 'One of my favorite moments in Paris was watching the sunset from the top of the Eiffel Tower. The view was breathtaking, and it made me appreciate the beauty of this city even more.',
        p2: 'Another highlight of my trip was visiting the Palace of Versailles, which is located just outside of Paris. The palace and its gardens are truly magnificent, and I highly recommend taking a guided tour to learn more about their history and significance.',
        p3: 'Overall, my week in Paris was a magical experience that I will never forget. I hope to return to this enchanting city someday and explore more of its wonders.',
        p4: ''
    },
    {
        id: '3',
        image: kevin,
        title: 'Exploring the African Jungle',
        date: '2022-01-01',
        author: 'John Doe',
        topP: 'Paris, the city of love and romance, is a dream destination for many travelers around the world. I recently had the opportunity to spend a week in this beautiful city, and it was an experience of a lifetime.',
        mainP: 'A Guide to Safely Experiencing the Wild This blog post will provide readers with an overview of the different types of jungle environments found in Africa, and the best ways to prepare for and experience these environments safely. It will cover topics such as wildlife encounters, equipment needed, and how to find reputable tour companies',
        guide: 'Sophie Martin',
        p1: 'One of my favorite moments in Paris was watching the sunset from the top of the Eiffel Tower. The view was breathtaking, and it made me appreciate the beauty of this city even more.',
        p2: 'Another highlight of my trip was visiting the Palace of Versailles, which is located just outside of Paris. The palace and its gardens are truly magnificent, and I highly recommend taking a guided tour to learn more about their history and significance.',
        p3: 'Overall, my week in Paris was a magical experience that I will never forget. I hope to return to this enchanting city someday and explore more of its wonders.',
        p4: ''
    },
    {
        id: '4',
        image: phillips,
        title: 'Card Title 4',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '5',
        image: kevin,
        title: 'Card Title 5',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '6',
        image: phillips,
        title: 'Card Title 6',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '7',
        image: kevin,
        title: 'Card Title 7',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '8',
        image: phillips,
        title: 'Card Title 8',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '9',
        image: kevin,
        title: 'Card Title 9',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '10',
        image: phillips,
        title: 'Card Title 10',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '11',
        image: kevin,
        title: 'Card Title 11',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '12',
        image: phillips,
        title: 'Card Title 12',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '13',
        image: kevin,
        title: 'Card Title 13',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '14',
        image: phillips,
        title: 'Card Title 14',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '15',
        image: kevin,
        title: 'Card Title 15',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '16',
        image: phillips,
        title: 'Card Title 16',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '17',
        image: kevin,
        title: 'Card Title 1',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '18',
        image: phillips,
        title: 'Card Title 2',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '19',
        image: kevin,
        title: 'Card Title 3',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '20',
        image: phillips,
        title: 'Card Title 4',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '21',
        image: kevin,
        title: 'Card Title 5',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '22',
        image: phillips,
        title: 'Card Title 6',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '23',
        image: kevin,
        title: 'Card Title 7',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '24',
        image: phillips,
        title: 'Card Title 8',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '25',
        image: kevin,
        title: 'Card Title 9',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '26',
        image: phillips,
        title: 'Card Title 10',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '27',
        image: kevin,
        title: 'Card Title 11',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '28',
        image: phillips,
        title: 'Card Title 12',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '29',
        image: kevin,
        title: 'Card Title 13',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        id: '30',
        image: phillips,
        title: 'Card Title 14',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        id: '31',
        image: kevin,
        title: 'Card Title 15',
        date: '2022-02-12',
        author: 'Admin',
    },
    // add more card data objects as needed
];
