import kevin from '../../images/kevin-mueller-aeNg4YA41P8-unsplash.jpg'
import phillips from '../../images/philipp-pilz-iQRKBNKyRpo-unsplash.jpg'

export const blogCardData = [
    {
        image: kevin,
        title: 'Card Title 1',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 2',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 3',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 4',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 5',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 6',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 7',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 8',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 9',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 10',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 11',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 12',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 13',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 14',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 15',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 16',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 1',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 2',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 3',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 4',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 5',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 6',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 7',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 8',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 9',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 10',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 11',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 12',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 13',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 14',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 15',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 16',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 1',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 2',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 3',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 4',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 5',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 6',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 7',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 8',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 9',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 10',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 11',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 12',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 13',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 14',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 15',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 16',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 1',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 2',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 3',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 4',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 5',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 6',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 7',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 8',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 9',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 10',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 11',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 12',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 13',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 14',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 15',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 16',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 1',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 2',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 3',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 4',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 5',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 6',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 7',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 8',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 9',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 10',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 11',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 12',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 13',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 14',
        date: '2022-02-14',
        author: 'Admin',
    },
    {
        image: kevin,
        title: 'Card Title 15',
        date: '2022-02-12',
        author: 'Admin',
    },
    {
        image: phillips,
        title: 'Card Title 16',
        date: '2022-02-14',
        author: 'Admin',
    },
    // add more card data objects as needed
];
